### ISSUE TITLE
FileNotFoundError：[Errno 2] No such file or directory: 'clustalw2 -quicktree -quiet -infile=out/TempFolder20201214175938/PDGFRA_variants.fasta'

### ISSUE THREAD

**Issue by BeyondMyPast228** [Moldia/multi_padlock_design#7]
Hi，
Thanks for developing this user-friendly tool. I installed the software on the basis of your guidline. When i run "**phython3 probedesign.py**" . Type "**human、input_human_genes.txt、20、20、65、75**”，Then，
An error occured:
Number of probes per gene (skip by pressing Enter):
<class 'FileNotFoundError'>
Traceback (most recent call last):
  File "probedesign.py", line 18, in <module>
    checkinput.getdesigninput()
  File "/home/zero/multi_padlock_design-2.1/lib/checkinput.py", line 222, in getdesigninput
    headers, basepos, sequences, msa, nocommon = retrieveseq.findseq(genes, hits, outdir_temp)
  File "/home/zero/multi_padlock_design-2.1/lib/retrieveseq.py", line 101, in findseq
    tempout = parmsa.continuemsa(dirname, msa)
  File "/home/zero/multi_padlock_design-2.1/lib/parmsa.py", line 113, in continuemsa
    runningmsa(dirname, msa)
  File "/home/zero/multi_padlock_design-2.1/lib/parmsa.py", line 105, in runningmsa
    runmsa(msafile)
  File "/home/zero/multi_padlock_design-2.1/lib/parmsa.py", line 19, in runmsa
    msa_process = subprocess.Popen("clustalw2 -quicktree -quiet -infile=" + msafile)
  File "/home/zero/miniconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/zero/miniconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'clustalw2 -quicktree -quiet -infile=out/TempFolder20201214175938/PDGFRA_variants.fasta'

I'm looking forward to your reply.

**Comment by lannyj** [comment]
Hi,
I encountered exactly the same issue as you did. I wonder if you have figured out a solution? Thank you.
